" Set fonts
set macligatures
" set guifont=Fira\ Code:h13
set guifont=Hasklig:h12
set linespace=2
set cursorline

" Disable scrollbars
set guioptions=

" Fixed window siz
set lines=32
set columns=106
