"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=/Users/bobbypriambodo/.vim/dein/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('/Users/bobbypriambodo/.vim/dein')
  call dein#begin('/Users/bobbypriambodo/.vim/dein')

  " Let dein manage dein
  " Required:
  call dein#add('/Users/bobbypriambodo/.vim/dein/repos/github.com/Shougo/dein.vim')

  " Add or remove your plugins here:
  call dein#add('Shougo/vimproc.vim', {
    \ 'build': {
    \     'windows': 'tools\\update-dll-mingw',
    \     'cygwin': 'make -f make_cygwin.mak',
    \     'mac': 'make -f make_mac.mak',
    \     'linux': 'make',
    \     'unix': 'gmake',
    \    },
    \ })

  " Essentials
  call dein#add('scrooloose/nerdtree', {'on_cmd': 'NERDTreeToggle'})
  call dein#add('tpope/vim-surround')
  call dein#add('tpope/vim-repeat')
  call dein#add('tpope/vim-fugitive')
  call dein#add('tpope/vim-commentary')
  call dein#add('jiangmiao/auto-pairs')
  call dein#add('ctrlpvim/ctrlp.vim')

  " Lightline status line
	call dein#add('itchyny/lightline.vim')

  " Nord theme
  call dein#add('arcticicestudio/nord-vim')

  " Required:
  call dein#end()
  call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable

" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif

"End dein Scripts-------------------------

filetype plugin indent on
syntax enable
set nu

" Colorscheme
color nord

" Encoding
set encoding=utf8

" Generic config
set expandtab                 " Use spaces instead of tabs
set tabstop=2                 " Use 2 spaces for tabs
set shiftwidth=2              " Use 2 spaces for tabs
set softtabstop=2             " Use 2 spaces for tabs
set autoread                  " Set to auto read when a file is changed from the outside
set ai                        " Auto indent
set nospell                   " Don't need spelling

" Trim trailing whitespace
autocmd BufWritePre * :%s/\s\+$//e

" Easy windows
map <C-J> <C-W>j
map <C-K> <C-W>k
map <C-L> <C-W>l
map <C-H> <C-W>h

" Easy move lines
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv

" Clear buffer
nmap <leader>b :bufdo bd<CR>

" CtrlP to CommandP
map <D-p> :CtrlP<CR>

" Ctrl+e to open nerdtree
map <C-e> :NERDTreeToggle<CR>

" Lightline configuration
let g:lightline = {
      \ 'colorscheme': 'nord',
			\ 'separator': { 'left': '', 'right': '' },
      \ 'subseparator': { 'left': '', 'right': '' }
      \ }
set laststatus=2

" OCaml Merlin configuration
let g:opamshare = substitute(system('opam config var share'),'\n$','','''')
execute "set rtp+=" . g:opamshare . "/merlin/vim"
