" VUNDLE SETUP START
set nocompatible              " be iMproved, required
filetype off                  " required
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
source ~/.vim/vundle-plugins
call vundle#end()             " required
filetype plugin indent on
" VUNDLE SETUP END

" Syntax highlighting
syntax on
" let g:solarized_termtrans=1
" let g:solarized_termcolors=256
colorscheme solarized
set background=dark

" Generic config
set nu                        " Line numbers on
set tabstop=2                 " Use 2 spaces for tabs
set shiftwidth=2              " Use 2 spaces for tabs
set softtabstop=2             " Use 2 spaces for tabs
set expandtab                 " Use spaces instead of tabs
set autoread                  " Set to auto read when a file is changed from the outside
set ruler                     " Always show current position
set ignorecase                " Ignore case when searching
set smartcase                 " When searching try to be smart about cases
set hlsearch                  " Highlight search results
set incsearch                 " Makes search act like search in modern browsers
set showmatch                 " Show matching brackets when text indicator is over them
set ai                        " Auto indent
set si                        " Smart indent
set wrap                      " Wrap lines
set laststatus=2              " Always show status bar

" No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500

" Configure backspace so it acts as it should act
set backspace=eol,start,indent
set whichwrap+=<,>,h,l

" Set utf8 as standard encoding and en_US as the standard language
set encoding=utf8

" Use Unix as the standard file type
set ffs=unix,dos,mac

" Avoid typos
noremap :W :w
noremap :Q :q

" Smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" NERDTree configs
map <C-n> :NERDTreeToggle<CR>           " Open NERDTree with ctrl+n

" open a NERDTree automatically when vim starts up if no files were specified
" autocmd StdinReadPre * let s:std_in=1
" autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" " Syntastic Config
" set statusline+=%#warningmsg#
" set statusline+=%{SyntasticStatuslineFlag()}
" set statusline+=%*

" let g:syntastic_always_populate_loc_list = 1
" let g:syntastic_auto_loc_list = 1
" let g:syntastic_check_on_open = 1
" let g:syntastic_check_on_wq = 0
" let g:syntastic_javascript_checkers = ['eslint']

" Use powerline fonts
let g:airline_powerline_fonts = 1
let g:airline_theme='solarized'
